### ISSUE TITLE
Using it within println hangs compilation

### ISSUE THREAD

**Issue by Fiedzia** [dtolnay/indoc#21]
println!(indoc!("hello world"));

hangs compilation

**Comment by dtolnay** [comment]
Thanks! Check out #17. As a workaround you can use `println!("{}", indoc!(...))` or use the `"unstable"` feature of indoc on a nightly compiler:

```toml
[dependencies]
indoc = { version = "0.2", features = ["unstable"] }
```

```rust
#![feature(proc_macro, proc_macro_non_items)]

extern crate indoc;
use indoc::indoc;

fn main() {
    println!(indoc!(""));
}
```
